name: Fetch and Process LMIA Reports

on:
  # Run automatically every day at 05:00 UTC
  schedule:
    - cron: '0 5 * * *'
  # Allow manual runs from the GitHub Actions tab
  workflow_dispatch:
    inputs:
      debug_mode:
        description: 'Enable debug mode for manual runs'
        required: false
        default: false
        type: boolean
      language:
        description: 'Language to process (en/fr)'
        required: false
        default: 'en'
        type: choice
        options:
          - en
          - fr
      update_cache:
        description: 'Run cache update after collection'
        required: false
        default: false
        type: boolean
      sleep_timer:
        description: 'Sleep timer between geocoding API calls (seconds)'
        required: false
        default: '1'
        type: string

# Add explicit permissions for the workflow
permissions:
  contents: write
  pull-requests: read

jobs:
  fetch-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Use GITHUB_TOKEN for authentication
          token: ${{ secrets.GITHUB_TOKEN }}
          # Fetch full history to avoid git issues
          fetch-depth: 0

      - name: Install dependencies (jq, csvkit)
        run: |
          sudo apt-get update
          sudo apt-get install -y jq csvkit
          # csvkit provides in2csv which is much lighter than gnumeric
          # and can handle XLSX to CSV conversion efficiently

      - name: Show debug info
        if: ${{ github.event.inputs.debug_mode == 'true' }}
        run: |
          echo "Debug mode enabled"
          echo "Repository: ${{ github.repository }}"
          echo "Branch: ${{ github.ref_name }}"
          echo "Commit: ${{ github.sha }}"
          echo "Actor: ${{ github.actor }}"

      - name: Fetch raw LMIA reports (no geocoding)
        id: collect
        run: |
          # Create the directory for the script if it doesn't exist
          mkdir -p scripts
          # Collect raw CSV files without postal code processing
          LANGUAGE="${{ github.event.inputs.language || 'en' }}" bash ./scripts/process_feeds.sh
          
      - name: Update location cache (optional)
        if: ${{ github.event.inputs.update_cache == 'true' }}
        run: |
          # Run cache update with configurable sleep timer
          SLEEP_TIMER="${{ github.event.inputs.sleep_timer || '1' }}" bash ./scripts/update_cache.sh
          
      - name: Generate cache statistics
        run: |
          # Always generate cache statistics (even if cache wasn't updated)
          if [ -f "./scripts/generate_cache_stats.sh" ]; then
            chmod +x ./scripts/generate_cache_stats.sh
            ./scripts/generate_cache_stats.sh
          else
            echo "Cache statistics generator not found"
          fi
      - name: Show process outputs
        if: ${{ github.event.inputs.debug_mode == 'true' }}
        run: |
          echo "Process outputs:"
          echo "new_files_found: ${{ steps.process.outputs.new_files_found }}"
          echo "new_file_names: ${{ steps.process.outputs.new_file_names }}"

      - name: Commit new files
        if: steps.process.outputs.new_files_found == 'true'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          # Add all changes
          git add .
          # The commit message will include a count of new files
          file_count=$(echo "${{ steps.process.outputs.new_file_names }}" | wc -w)
          git commit -m "Bot: Add ${file_count} new LMIA report(s)" -m "${{ steps.process.outputs.new_file_names }}"
          # Force push to avoid conflicts (since this is a bot workflow)
          git push origin ${{ github.ref_name }} --force-with-lease

      - name: Manual run summary
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "=== Manual Run Summary ==="
          echo "Run completed at: $(date)"
          echo "New files found: ${{ steps.process.outputs.new_files_found }}"
          if [ "${{ steps.process.outputs.new_files_found }}" = "true" ]; then
            echo "Files added: ${{ steps.process.outputs.new_file_names }}"
          else
            echo "No new files were found to process"
          fi